routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RegistrationController;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('search');
});


Route::middleware('auth')->name('user.')->group(function () {
    Route::get('/profile', function () {

        return view('profile', ['user' => Auth::user()]);
    })->name('profile');



    Route::get('/login', function () {
        if (Auth::check())
            return redirect()->route('user.profile');
        return view('login');
    })->withoutMiddleware('auth')->name('login');

    Route::post('/login', [\App\Http\Controllers\LoginController::class, 'login'])
        ->withoutMiddleware('auth');

    Route::get('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

    Route::get('/registration', function () {
        if (Auth::user())
            return redirect()->route('user.profile');
        return view('registration');
    })->withoutMiddleware('auth')->name('registration');

    Route::post('/registration', [RegistrationController::class, 'userRegistration'])
        ->withoutMiddleware('auth');


    Route::name('update.')->prefix('/profile/update')->group(function(){

        Route::post('/passport-data', [UserController::class, 'updateInfo'])
            ->name('passport-data');

        Route::post('/profile-picture', [UserController::class, 'setUserPhoto'])
            ->name('profile-picture');

        Route::post('/password', [UserController::class, 'updatePassword'])
            ->name('password');

        Route::post('/email', [UserController::class, 'updateEmail'])
            ->name('email');

        Route::post('/teacher-about', [\App\Http\Controllers\TeacherController::class, 'update'])
            ->name('teacher-about');


    });


    Route::get('/profile/register-student', function () {
        if (Auth::user()->isParent())
            return view('registration', ['isCreateStudent' => true]);
        return redirect()->route('user.registration');
    })
        ->name('student-registration');

    Route::post('/profile/register-student', [RegistrationController::class, 'childRegistration']);

    Route::get('/profile/login-as-{id}',
        [\App\Http\Controllers\LoginController::class, 'loginAsChild'])
        ->name('login-as-child');

    Route::get('/profile/become-teacher',[UserController::class, 'becomeTeacher'])->name('become-teacher');

    Route::get('/profile/become-parent',[UserController::class, 'becomeParent'])->name('become-parent');

    Route::post('/add-review/{id}',[\App\Http\Controllers\TeacherReviewController::class,'store'])
        ->name('add-review');

    Route::get('/delete-review/{id}', [\App\Http\Controllers\TeacherReviewController::class, 'destroy'])
        ->name('delete-review');

    Route::post('/update-review/{id}', [\App\Http\Controllers\TeacherReviewController::class, 'update'])
        ->name('update-review');

    Route::get('/open-chat-{id}', [\App\Http\Controllers\ChatController::class, 'openChat']
    )->name('open-chat');


    Route::get('/chat/rooms',
        [\App\Http\Controllers\ChatController::class, 'rooms']
    )->name('chat-rooms');

    Route::get('/chat/{id}/messages', [\App\Http\Controllers\ChatController::class, 'messages']);

    Route::get('/chat/{id}',[\App\Http\Controllers\ChatController::class, 'index']
    )->name('chat-room');


    Route::post('/chat/{id}/messages',[\App\Http\Controllers\ChatController::class, 'store']
    );

    Route::get('/chat/', [\App\Http\Controllers\ChatController::class, 'index']
    )->name('chat');

});




Route::get('/search', [\App\Http\Controllers\SearchController::class, 'show'])->name('search');

Route::get('/teachers/{id}', [\App\Http\Controllers\TeacherPageController::class,'index'])->name('user-page');

resources/views/chat.blade.php
@extends('layouts.app')

@section('title')
    Страница пользователя
@endsection



@section('content')
    <div class="container-fluid row h-100 ">
        <div class="col-3 border-end  h-100" style="overflow: auto">
{{--            @for($i=0; $i<10; $i++)--}}
{{--            @foreach($rooms as $roomItem)--}}
{{--                <a href="{{route('user.chat-room', ['id' => $roomItem->id])}}" class="text-reset text-decoration-none">--}}
{{--                <div class="bg-light mt-1 container">--}}
{{--                    <div class="row">--}}
{{--                        <span class="text-start">--}}
{{--                            {{$roomItem->anotherUser->where('user_id','!=', \Illuminate\Support\Facades\Auth::user()->id)->first()->name}}--}}
{{--                        </span>--}}
{{--                    </div>--}}
{{--                    <div class="row"> {{$roomItem->lastMessage->message}}--}}
{{--                        <span class="text-end">{{$roomItem->lastMessage->created_at}} </span>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                </a>--}}

{{--            @endforeach--}}
{{--            @endfor--}}

                <buttton class="btn btn-light w-100">Загрузить еще</buttton>
        </div>
        <div class="col ">
            @isset($room)
            <div class="row bg-body border-bottom">

                <p class=" text-center h3">
                    {{$room->anotherUser->where('user_id','!=', \Illuminate\Support\Facades\Auth::user()->id)->first()->name}}
                    {{$room->anotherUser->where('user_id','!=', \Illuminate\Support\Facades\Auth::user()->id)->first()->last_name}}
                </p>
            </div>
            <div class="row   position-relative"
            style="height: calc(100vh - 127px)"

            >

                <div class=" flex-grow-0 py-3 px-4   "
                style="position : absolute; bottom   : 0"
                >
                    <div style="overflow: auto;  height: calc(100vh - 215px)">
                        <buttton class="btn btn-light w-100">Загрузить еще</buttton>

                        @foreach($room->messages as $message)

                            <p style="color:dodgerblue"> {{$message->user->name}} @if($message->user->isTeacher()) {{$message->user->middle_name}}@endif</p>
                            <p>{{$message->message}} </p>
                        @endforeach



                    </div>
                    <form class="input-group border-top" method="post" action="{{route('user.chat-room', ['id' =>$room->id])}}">
                        @csrf
                        <textarea type="text" class="form-control" name="message" placeholder="Введите ваше сообщение"></textarea>
                        <button class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
            @else
                <div class="row h-100 ">
                <p class="text-center h3 align-middle">Выберите чат</p>
                </div>
            @endisset
        </div>

    </div>
@endsection

resources/views/login.blade.php
@extends('layouts.app')

@section('title')
   Вход
@endsection



@section('content')
    <p class="text-center h2"> Вход</p>

    <form method="post" action="/login" class="form-control w-50  container-fluid" >
        @csrf
        @if(session('error'))
            <p class=" alert-danger"> {{session('error')}}</p>
     @endif
        <!-- Email input -->
        <div class="form-outline mb-4">
            <input class="form-control" id="email" name="email" type="text" placeholder="Email">
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <input class="form-control" id="password" name="password" type="password" value="" placeholder="Пароль" autocomplete="new-password">
        </div>

        <!-- 2 column grid layout for inline styling -->



        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Войти</button>
    </form>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('title')
    Приватная страница
@endsection



@section('content')
    <div class="row">
        <div class="col">
            <p class="h1">
                <img
                    src="{{$user->getProfilePicturePath()}}"
                    class="img-thumbnail rounded-circle mr-3"
                    alt=""
                    width="100"
                    height="100"
                >
                {{$user->name}} {{$user->last_name}}
            </p>


            @if(Session::get('image_updated'))
                <p class="text-success">Изобажение успешно обновлено</p>
            @endif
            <p>{{$user->role()}}</p>
            <form class="card-body" action="{{route('user.update.profile-picture')}}"
                  method="post"
                  enctype="multipart/form-data"
            >
                @csrf
                <p class="h3">Фото профиля</p>
                @error('profile_image')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input type="file" name="profile_image">
                <button type="submit" class="btn btn-success">изменить фото</button>
            </form>
            <form class="container-fluid" method="post" action="{{route('user.update.passport-data')}}">
                @csrf
                <p class="h3">Персональная информация</p>
                @if(Session::get('passport-data.success'))`
                <div class="alert alert-success">{{Session::get('passport-data.success')}}</div>
                @endif

                <label for="last_name">Фамилия</label>
                @error('last_name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input class="input-group-text w-100" id="last_name" name="last_name" value="{{$user->last_name}}">

                <label for="name">Имя</label>
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input class="input-group-text w-100" id="name" name="name" value="{{$user->name}}">

                <label for="middle_name">Отчество</label>
                @error('middle_name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input class="input-group-text w-100" id="middle_name" name="middle_name"
                       value="{{$user->middle_name}}">

                <label for="birthdate">Дата рождения</label>

                @error('birthdate')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input type="date" class="form-control" value="{{$user->birthdate}}" name="birthdate">


                <button class="btn btn-secondary">Изменить</button>
                <hr>
            </form>

            @if(!$user->isStudent())
                <div class="container-fluid">
                    <p class="h3">Пареметры родителя</p>
                    @if($user->isParent())
                        @if(Session::get('createdNewUser'))`
                        <div class="alert alert-success">{{Session::get('createdNewUser')}}</div>
                        @endif
                        @forelse ($user->children as $child)
                            <p>
                                <a href="{{route('user.login-as-child',['id' => $child->id])}}">
                                    {{$child->name}} {{$child->last_name}}@if(!$loop->last),@endif
                                </a>
                            </p>

                        @empty
                            <p>У вас нет детей</p>
                        @endforelse
                        <p><a href="{{route('user.student-registration')}}">Вы можете создать аккаунт для ребенка</a>
                        </p>

                    @else
                        <a href="{{route('user.become-parent')}}">вы можете стать родителем</a>
                    @endif
                    <hr>
                </div>
            @endif
            <div class="container-fluid">
                <p class="h3">Параметры репетитора</p>
                @if($user->isTeacher())
                    <form class="w-100" method="post" action="{{route('user.update.teacher-about')}}">
                        @csrf

                        @if(Session::get('teacher.success'))`
                        <div class="alert alert-success">{{Session::get('teacher.success')}}</div>
                        @endif

                        <label for="education_id">Образование</label>
                        @error('education_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <select name="education_id" class="form-select">
                            <option value="">не выбрано</option>
                            @foreach( \App\Models\Education::get() as $education)
                                <option value="{{$education->id}}"
                                        @if($education->id == $user->teacherRole->education_id)
                                        selected
                                    @endif
                                >  {{$education-> name}}</option>
                            @endforeach
                        </select>


                        <label for="about">О себе</label>
                        @error('about')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <textarea class="form-control" id="about" name="about" rows="4"
                        >{{$user->teacherRole->about}}</textarea>

                        <label for="work_experience">Опыт работы</label>
                        @error('work_experience')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <number-component :prop="{{Auth::user()->teacherRole->work_experience}}"
                        :name="'work_experience'"
                        ></number-component>

                        <label>Направления</label> <br>
                        <div class="container-fluid ">
                                <select-subject  :start-values="{{json_encode(Auth::user()->teacherRole->subjectIds())}}"
                                                 :categories="{{\App\Models\Category::with('subjects')->get()}}"
                                                 :prices="{{json_encode(Auth::user()->teacherRole->getPrices())}}"
                                >

                                </select-subject>
                        </div>
                        <label>Ключевые слова</label>
                        <textarea class="form-control" name="keywords">{{Auth::user()->teacherRole->keywords}}</textarea>
                        <button class="btn btn-secondary">Изменить</button>
                        <hr>
                    </form>
                @else
                    <a href="{{route('user.become-teacher')}}"> Вы можете стать учителем</a>
                @endif
            </div>


            <form class="container-fluid" method="post" action="{{route('user.update.password')}}">
                @csrf
                <p class="h3">Безопасность</p>
                @if(Session::get('password.success'))
                    <div class="alert alert-success">{{Session::get('password.success')}}</div>
                @endif
                <label for="current_password">текущий пароль</label>
                @error('current_password')
                <div class="alert alert-danger">{{ $message}}</div>
                @enderror
                <input class="input-group-text w-100" id="current_password" name="current_password" type="password" autocomplete="new-password">

                <label for="new_password">новый пароль</label>
                @error('new_password')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <input class="input-group-text w-100" id="new_password" name="new_password" type="password" autocomplete="new-password">

                <label for="new_password_confirmation">новый пароль еще раз</label>
                <input class="input-group-text w-100" id="new_password_confirmation"
                       name="new_password_confirmation"
                       autocomplete="new-password"
                       type="password">
                <button class="btn btn-secondary">Изменить</button>
                <hr>
            </form>
            <form class="container-fluid" method="post" action="{{route('user.update.email')}}">
                @csrf
                @error('email')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                @if(Session::get('email.success'))
                    <div class="alert alert-success">{{Session::get('email.success')}}</div>
                @endif
                <p class="h3">Email</p>
                <label for="email">email</label>
                <input class="input-group-text w-100" id="email" name="email" value="{{$user->email}}">
                <button class="btn btn-secondary">Изменить</button>
                <hr>
            </form>
        </div>
    </div>
@endsection

resources/views/registration.blade.php
@extends('layouts.app')

@section('title')
    Регистрация пользователя
@endsection





@section('content')
    <form class="col-10 container-fluid" method="post" action="
        @if( isset($isCreateStudent) && $isCreateStudent)
    {{route('user.student-registration')}}
    @else
    {{route('user.registration')}}
    @endif
    {{--    {{route('user.registration')}}--}}
        ">
        @csrf
        <p class="h2 text-center">Регистрация пользователя</p>

{{--        @if ($errors->any())--}}
{{--            <div class="alert alert-danger">--}}
{{--                <ul>--}}
{{--                    @foreach ($errors->all() as $error)--}}
{{--                        <li>{{ $error }}</li>--}}
{{--                    @endforeach--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        @endif--}}

        <label for="email" l> Почта:</label>
        @error('email')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <input type="text" class="form-control w-75" name="email" id="email">

        <label for="password"> Пароль:</label>
        @error('password')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <input type="password" class="form-control w-75" name="password" id="password" autocomplete="new-password">

        <label for="password_confirm"> Пароль еще раз:</label>
        <input type="password" class="form-control w-75" name="password_confirmation" id="password_confirm">
        @error('last_name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="last_name"> Фамилия:</label>

        <input type="text" class="form-control w-75" name="last_name" id="last_name">

        <label for="name"> Имя:</label>
        @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <input type="text" class="form-control w-75" name="name" id="name">

        <label for="middle_name"> Отчество:</label>
        @error('middle_name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <input type="text" class="form-control w-75" name="middle_name" id="middle_name">

        <label for="birthdate">Дата рождения</label>
        @error('birthdate')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <input type="date" class="form-control w-75"  name="birthdate">

        @if( !isset($isCreateStudent))
            <label>Тип пользователя</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="usertype" id="parent" value="parent">
                <label class="form-check-label" for="parent">Родитель </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="usertype" id="student" value="student" checked>
                <label class="form-check-label" for="student"> Обычный пользователь</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="usertype" id="teacher" value="teacher">
                <label class="form-check-label" for="teacher"> Преподаватель </label>
            </div>
        @endif
        <button class="btn btn-primary">Зарегистрировать аккаунт</button>
    </form>

@endsection

resources/views/search.blade.php
@extends('layouts.app')

@section('title')
    Поиск репетитора
@endsection

@section('search-page')
    <div class="container-fluid">
        <form class="row" method="get" action="{{route('search')}}">
            <div class="col-2 bg-white">
                <div class="row">

                    <label for="education">Образование</label>
                    <select name="education" class="form-select">
                        <option value="">не выбрано</option>
                        @foreach( \App\Models\Education::get() as $education)
                            <option value="{{$education->id}}"
                                    @if( isset($request["education"]) && $education->id == $request["education"])
                                        selected
                                        @endif
                            >  {{$education-> name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="row">
                    <div class="row">
                        <label>Цена</label>
                        <label for="min_price">от</label>

                        <number-component :prop="{{ $request['min_price'] ?? 0}}"
                                          :name="'min_price'"
                        ></number-component>
                    </div>
                    <div class="row">
                        <label for="max_price">до</label>

                        <number-component :prop="{{ $request['max_price'] ?? 0}}"
                                          :name="'max_price'"
                        ></number-component>
                    </div>
                </div>
                <div class="row">
                    <div class="row">
                        <label>Опыт работы</label>
                        <label for="min_work_experience">от</label>
{{--                        <input class="input-group"  name="min_work_experience" placeholder="от"--}}
{{--                               @isset($request['min_work_experience'])--}}
{{--                                   value="{{$request['min_work_experience']}}"--}}
{{--                            @endisset--}}
{{--                        >--}}
                        <number-component :prop="{{ $request['min_work_experience'] ?? 0}}"
                                          :name="'min_work_experience'"
                        ></number-component>
                    </div>
{{--                    <div class="row">--}}
{{--                        <label for="max_work_experience">до</label>--}}
{{--                        <input class="input-group-sm" placeholder="до" name="max_work_experience">--}}

{{--                    </div>--}}
                </div>
                <first-app :categories="{{\App\Models\Category::with('subjects')->get()}}"
                          @isset($request['subject']) :subject-id="{{$request['subject']}}" @endisset
                           @isset($request['category'])    :category-id="{{$request['category']}}" @endisset
                >
                </first-app>
                <div class="row">
                <label>Сортировать по</label>
                <select class="form-select" name="order" @isset($request['order']) value="{{$request['order']}}" @endisset>
{{--                    <option value="price_asc">возрастанию цены</option>--}}
                    <option value="created_at">дате создания</option>
                    <option value="reviews_count">количеству отзывов</option>
                    <option value="reviews_avg">оценкам отзывов</option>
                </select>
                </div>
                <button class="btn btn-success">Найти</button>
            </div>


            <div class="col-9 bg-white">
                <div class="row">
                <label for="q">Запрос</label>
                <div class="input-group mb-3">

                    <input type="text" class="form-control"  name="q" placeholder="поиск"
                           @isset($request['q'])
                               value="{{$request['q']}}"
                           @endisset
                           aria-label="Recipient's username" aria-describedby="basic-addon2">
                    </div>
                    <div class="row" style="margin-top: 10px">

                        @if($teachers->total() > 0)

                           @foreach($teachers as $teacher)
                                <div style="width: 90%; background-color: #fff; margin: 0 auto; border:1px solid; margin-bottom: 10px " class="rounded ">
                                    <div class="container row">
                                        <div class="col">
                                            <a href="{{route('user-page',['id' => $teacher->id])}}" style="color: inherit">
                                                {{$teacher->user->name}} {{$teacher->user->last_name}}</a>
                                        </div>


                                      </div>

                                    <div class="container row">
                                    <div class="col-1">

                                            <img
                                               src="{{$teacher->user->getProfilePicturePath()}}"
                                                class="img-thumbnail rounded-circle mr-3"
                                                alt=""
                                                width="75"
                                                height="75"
                                            >


                                        <div class="row">    {{$teacher->getReviewsCount()}} |
                                          ср. оценка  {{(int)$teacher->teacherReviews()->avg('score')}}
                                        </div>
                                    </div>
                                        <div class="col">

                                            <div class="row"> <span> О себе: {{$teacher->about}}</span></div>
                                            <div class="row">
                                                @foreach($teacher->getAllCategoriesAndSubjects() as $category)

                                                    Категория: {{$category['name']}}<br>
                                                Преметы:
                                                    @foreach($category['attributes'] as $subject)
                                                        {{$subject['name']}}  @if($subject['price']) {{$subject['price']}} руб/ч@endif <br>
                                                    @endforeach
                                                    <br>
                                                @endforeach

                                            </div>
                                        </div>
                                        <div class="col-1"> образование
                                            @if (isset($teacher->education->name))
                                                {{$teacher->education->name}}
                                            @endif

                                        </div>
                                    </div>
                                </div>

                            @endforeach
                               {{($teachers->links('layouts.pagination'))}}
                        @else
                            <p class="text-center h4" style="color:grey">  по вашему запросу ничего не найдено </p>


                        @endif

                    </div>
                </div>
        </div>
    </form>

</div>
@endsection

resources/views/test.blade.php
@extends('layouts.app')

@section('title')
    Чат
@endsection



@section('content')
<chat-list

@isset($room)
    :current-room="{{$room}}"
@endisset


></chat-list>

@endsection

resources/views/user-page.blade.php
@extends('layouts.app')

@section('title')
    Страница пользователя
@endsection



@section('content')
    <p class="h2"> {{$teacher->user->name}}   {{$teacher->user->last_name}}</p>
    <p class="h3">О себе</p>
    <p>{{$teacher->about}}</p>
<a class="btn btn-danger" href="{{route('user.open-chat', ['id' => $teacher->id])}}">Открыть чат</a><br>
    @foreach($teacher->getAllCategoriesAndSubjects() as $category)

        Категория: {{$category['name']}}<br>
        Преметы:
        @foreach($category['attributes'] as $subject)
            {{$subject['name']}}  @if($subject['price']) {{$subject['price']}} руб/ч@endif <br>
        @endforeach
        <br>
    @endforeach

    <hr>
    <p class="h3">Отзывы ({{$reviews->total()}})</p>
    @if(\Illuminate\Support\Facades\Auth::check())
        <form method="post" action="{{$route}}">

            @csrf
            <select name="score" class="form-select">
                @for($i=1; $i <=5; $i++)
                    <option @if(isset($userReview['score']) && $i == $userReview['score']) selected @endif>{{$i}}</option>
                @endfor
            </select>
            <textarea name="comment" class="form-control">@isset($userReview['comment']){{$userReview['comment']}}@endisset</textarea>
            @empty($userReview)
            <button class="btn btn-success"> Отправить отзыв</button>
            @else
                <button class="btn btn-success"> Изменить отзыв</button>
                <a class="btn btn-danger" href="{{route('user.delete-review', ['id' => $userReview['id']])}}">Удалить отзыв</a>
            @endempty

        </form>
    @else
        <div class="container alert alert-danger"><a href="{{route('user.login')}}">Авторизируйтесь</a>, чтобы оставлять отзывы
        </div>
    @endif
    <div class="container">
            @foreach($reviews as $review)
                <div class="container bg-light mb-3" style="border: 1px solid #000000; ">
                    <div class="row border-bottom">
                        <div class="col">{{$review->author->name}} {{$review->author->last_name}}</div>
                        <div class="col text-end">оценка: {{$review->score}} </div>
                    </div>
                    <div class="row"> {{$review->comment}}</div>
                </div>
            @endforeach
                {{($reviews->links('layouts.pagination'))}}
    </div>
    {{--<teacher-review :reviews="{{json_encode($reviews)}}"></teacher-review>--}}

@endsection